//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commercial_company_project.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyPermission
    {
        public int OrderNumber { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> MeasreuingUnit { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual MeasruingUnit MeasruingUnit { get; set; }
        public virtual Store Store { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
